### ISSUE TITLE
Please complete the manifest

### ISSUE THREAD

**Issue by jise** [mcarr823/keep-teams-awake#1]
Please complete the manifest so that the extension icon is correctly displayed everywhere. 😇

Note that the first line is your manually installed extension that has a few missing lines added to the manifest, and the second line is your original extension installed from the Chrome store:
![Image](https://github.com/user-attachments/assets/be346b31-ef78-40e3-80bb-adaf6735adbd)

This section is missing in the manifest, please add it:
![Image](https://github.com/user-attachments/assets/0ddc3587-ad44-4f8b-abb3-faf2e2d4e664)

About required icon sizes:
https://developer.chrome.com/docs/extensions/reference/manifest/icons

---
KeepTeamsAwake 1.0
Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36

**Comment by mcarr823** [comment]
Thanks jise, this should now be fixed in commit 1ba9b52a2086f045fc4bfe47f91628dc4b9ebf7e
I'll upload a new build to the stores shortly.

**Comment by jise** [comment]
Hi mcarr823, unfortunately this fix didn't fix anything, because you need to keep the icon sizes in both sections of the manifest the same, as I had in my example. Just delete the highlighted piece of text, or conversely add the missing icon sizes in the "default_icon" section. But I'm leaning towards deleting the highlighted text because those giant iconc sizes are unnecessary, see [About required icon sizes](https://developer.chrome.com/docs/extensions/reference/manifest/icons).

![Image](https://github.com/user-attachments/assets/3ae60703-37cc-4c68-8259-ed5715b5c1ea)

---
KeepTeamsAwake 1.0.1
Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36

**Comment by mcarr823** [comment]
Gotcha. I'll submit a new build with the icons matching.

**Comment by jise** [comment]
Hi mcarr823, I see your Commit [7fd5bb9](https://github.com/mcarr823/keep-teams-awake/commit/7fd5bb9a40eebbb30df824241bdf420292ac7f84), which is perfectly fine and should solve the problem.

I received an update from the Chrome web store a while ago:
![Image](https://github.com/user-attachments/assets/db395b3a-6cf7-418a-86f4-f5209ed843a6)

But the manifest is still in version 1.0.1 unchanged, even though the store lists version 1.0.2. I have no idea what could have caused it, but I'm reporting it to you just in case. 😇

---
KeepTeamsAwake 1.0.2
Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36

**Comment by mcarr823** [comment]
Thanks jise, that's odd. I'll look into it.

**Comment by jise** [comment]
Hi mcarr823,

Today, out of curiosity, I checked the Chrome web store to see if the problem still exists and to my surprise the manifest is already up to date, but since the app version remained the same 1.0.2, there was of course no update.
https://robwu.nl/crxviewer/?crx=acofimfooiojfhnokmddfgmlfnjnhobp

![Image](https://github.com/user-attachments/assets/a001665f-f279-4916-8fbd-7f6b01366099)

So I downloaded the zipped archive with the application and installed it manually and again no change. Then I thought, what if the problem is those gigantic icons, which we know are de facto useless. Yes, it was confirmed, all I had to do was to delete the two lines with the biggest 1024.png icon in the manifest as the first step, refresh the extension and it was immediately Ok.

So now you know what the next two steps should be, increase the version and throw out the biggest icon. 

---
KeepTeamsAwake 1.0.2
Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36

**Comment by jise** [comment]
I'm sorry, I just want to draw your attention to my previous post. 🙏

**Comment by jise** [comment]
I just want to draw your attention to my previous posts. 😇🙏
